# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_auto_20170725_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupdate',
            name='user_feedback',
            field=models.CharField(max_length=600),
        ),
    ]
