# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_auto_20170726_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickupdate',
            old_name='food_weight',
            new_name='pickup_comment',
        ),
        migrations.RenameField(
            model_name='pickupdate',
            old_name='user_feedback',
            new_name='pickup_feedback',
        ),
        migrations.RenameField(
            model_name='pickupdate',
            old_name='user_comment',
            new_name='pickup_weight',
        ),
    ]
